(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 45)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 47)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 48)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 49)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 51)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 53)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 56)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 57)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 58)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 59)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 60)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 61)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 62)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 63)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 64)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 65)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 66)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 67)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 68)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 69)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 70)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 71)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 72)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 73)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 74)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 75)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 76)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 77)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 78)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 79)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 80)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 81)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 82)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 83)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 84)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 85)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 87)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 88)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 89)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 90)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 91)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 92)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 93)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 94)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 95)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 96)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 97)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 98)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 99)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 100)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 101)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 102)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 103)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 104)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 105)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 106)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 107)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 108)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 109)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 110)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 111)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 112)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 113)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 114)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 115)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 116)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 117)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 118)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 119)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 120)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 121)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 122)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 123)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 124)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 125)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 126)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 127)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 128)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 129)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 130)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 133)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 134)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 135)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 136)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 137)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 138)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 139)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 140)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 141)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 142)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 143)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 144)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 145)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 146)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 147)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 148)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 149)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 150)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 151)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 152)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 153)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 154)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 155)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 156)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 157)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 158)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 159)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 160)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 161)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 162)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 163)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 164)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 165)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 166)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 167)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 168)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 169)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 170)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 171)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 172)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 173)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 174)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 175)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 176)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 177)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 178)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 179)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 180)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 181)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 182)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 183)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 184)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 185)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 186)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 187)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 188)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 189)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 190)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 191)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 192)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 193)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 194)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 195)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 196)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 197)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 198)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 199)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 200)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 201)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 202)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 203)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 204)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 205)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 206)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 207)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 208)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 209)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 210)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 211)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 212)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 213)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 214)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 215)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 216)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 217)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 218)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 219)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 220)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 221)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 222)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 223)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 224)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 225)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 226)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 227)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 228)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 229)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 230)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 231)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 232)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 233)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 234)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 235)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 236)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 237)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 238)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 239)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 240)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 241)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 242)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 243)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 244)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 245)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 246)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 247)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 248)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 249)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 250)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 251)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 252)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 253)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 254)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 255)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 256)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 257)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 258)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 259)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 260)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 261)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 262)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 263)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 264)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 265)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 266)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 267)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 268)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 269)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 270)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 271)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 272)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 273)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 274)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 275)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 276)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 277)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 278)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 279)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 280)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 281)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 282)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 283)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 284)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 285)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 286)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 287)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 288)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 289)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 290)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 291)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 292)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 293)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 294)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 295)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 296)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 297)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 298)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 299)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 300)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 301)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 302)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 303)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 304)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 305)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 306)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 307)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 308)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 309)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 310)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 311)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 312)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 313)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 314)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 315)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 316)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 317)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 318)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 319)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 320)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 321)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 322)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 323)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 324)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 325)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 326)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 327)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 328)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 329)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 330)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 331)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 332)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 333)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 334)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 335)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 336)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 337)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 338)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 339)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
    at runNextTicks (internal/process/task_queues.js:55:5)
    at processImmediate (internal/timers.js:412:9)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 340)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 341)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 342)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 343)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 344)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 345)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 346)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 347)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 348)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 349)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 350)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 351)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 352)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 353)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 354)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 355)
(node:5916) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at C:\Projects\NitroPDA\sql\sqllib.js:114:48
    at C:\Projects\NitroPDA\node_modules\mssql\lib\base\connection-pool.js:237:9
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 356)
